#!/bin/bash
export HETU_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export LD_LIBRARY_PATH="${HETU_HOME}/build/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="${HETU_HOME}/python/hetu/rpc:${HETU_HOME}/python:${HETU_HOME}/build/lib:${PYTHONPATH}"
export GRPC_CMAKE_PREFIX_PATH=/home/gehao/njw1123/hetu_add_torch/install
export LD_LIBRARY_PATH=/home/gehao/njw1123/torch_1_13/torch/lib:$LD_LIBRARY_PATH
export PYTHONPATH="/home/gehao/njw1123/torch_1_13:${PYTHONPATH}"
# export LD_LIBRARY_PATH=/home/gehao/njw1123/hetu_add_torch/install/lib:$LD_LIBRARY_PATH
